# name: Build

# on:
#   push:
#   pull_request:
#   schedule:
#     - cron: "0 0 * * *"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     container: zephyrprojectrtos/ci:latest
#     env:
#       CMAKE_PREFIX_PATH: /opt/toolchains
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           path: firmware

#       - name: Initialize
#         working-directory: firmware
#         run: |
#           west init -l .
#           west update

#       - name: Build firmware
#         working-directory: firmware
#         run: |
#           west build -b rpi_pico app

#       - name: Twister Tests
#         working-directory: firmware
#         run: |
#           ../zephyr/scripts/twister -G --board-root boards/ --testsuite-root ./tests/

#       - name: Archive firmware
#         uses: actions/upload-artifact@v2
#         with:
#           name: firmware
#           path: firmware/build/zephyr/zephyr.*
